# Generated by Django 6.0.2 on 2026-02-14 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('clinic_type', models.CharField(choices=[('PRIVATE', 'Private'), ('CORPORATE', 'Corporate'), ('MOBILE', 'Mobile'), ('ANIMAL_SHELTER', 'Animal Shelter'), ('TEACHING_HOSPITAL', 'Teaching Hospital'), ('WILDLIFE_FACILITY', 'Wildlife Facility')], max_length=50)),
                ('species_types', models.CharField(choices=[('SMALL_ANIMAL', 'Small Animal'), ('EQUINE', 'Equine'), ('FELINE', 'Feline'), ('MIXED', 'Mixed'), ('EXOTIC_AND_AVIAN', 'Exotic and Avian')], max_length=50)),
                ('service_types', models.CharField(choices=[('GENERAL_VETERINARY_CARE', 'General Veterinary Care'), ('EMERGENCY_OR_CRITICAL_CARE', 'Emergency or Critical Care'), ('URGENT_CARE', 'Urgent Care'), ('SPECIALTY_SERVICES', 'Specialty Services'), ('MOBILE_VETERINARY_SERVICES', 'Mobile Veterinary Services'), ('ANIMAL_SHELTER_SERVICES', 'Animal Shelter Services'), ('TEACHING_HOSPITAL_SERVICES', 'Teaching Hospital Services'), ('WILDLIFE_FACILITY_SERVICES', 'Wildlife Facility Services')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('flood_risk', models.IntegerField(default=0)),
                ('wildfire_risk', models.IntegerField(default=0)),
                ('heatwave_risk', models.IntegerField(default=0)),
                ('power_outage_risk', models.IntegerField(default=0)),
                ('air_pollution_risk', models.IntegerField(default=0)),
                ('erosion_risk', models.IntegerField(default=0)),
                ('hurricane_risk', models.IntegerField(default=0)),
                ('tornado_risk', models.IntegerField(default=0)),
                ('cold_wave_risk', models.IntegerField(default=0)),
                ('blizzard_risk', models.IntegerField(default=0)),
                ('earthquake_risk', models.IntegerField(default=0)),
                ('avalanche_risk', models.IntegerField(default=0)),
                ('assessment_data', models.JSONField(default=dict)),
                ('vulnerabilities', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='clinics.clinic')),
            ],
        ),
    ]
