# Generated by Django 6.0.2 on 2026-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('CORPORATE', 'Corporate'), ('MOBILE', 'Mobile'), ('ANIMAL_SHELTER', 'Animal Shelter'), ('TEACHING_HOSPITAL', 'Teaching Hospital'), ('WILDLIFE_FACILITY', 'Wildlife Facility'), ('SMALL_ANIMAL_CLINIC', 'Small Animal Clinic'), ('LARGE_ANIMAL_CLINIC', 'Large Animal Clinic'), ('MIXED_ANIMAL_CLINIC', 'Mixed Animal Clinic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='species_types',
            field=models.CharField(choices=[('SMALL_ANIMAL', 'Small Animal'), ('LARGE_ANIMAL', 'Large Animal'), ('EQUINE', 'Equine'), ('FELINE', 'Feline'), ('MIXED', 'Mixed'), ('EXOTIC_AND_AVIAN', 'Exotic and Avian')], max_length=50),
        ),
    ]
