# Generated by Django 6.0.2 on 2026-02-14 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FLOOD', 'Flood'), ('WILDFIRE', 'Wildfire'), ('HEATWAVE', 'Heatwave'), ('POWER_OUTAGE', 'Power Outage'), ('AIR_POLLUTION', 'Air Pollution'), ('EROSION', 'Erosion'), ('HURRICANE', 'Hurricane'), ('TORNADO', 'Tornado'), ('COLD_WAVE', 'Cold Wave'), ('BLIZZARD', 'Blizzard'), ('EARTHQUAKE', 'Earthquake'), ('AVALANCHE', 'Avalanche')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('common_regions', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='DisasterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preparation_steps', models.JSONField(default=list)),
                ('response_steps', models.JSONField(default=list)),
                ('recovery_steps', models.JSONField(default=list)),
                ('emergency_contacts', models.JSONField(default=list)),
                ('supplies_needed', models.JSONField(default=list)),
                ('training_requirements', models.JSONField(default=list)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaster_plans', to='clinics.clinic')),
                ('disaster_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasterplans.disastertype')),
            ],
        ),
    ]
