# Generated by Django 6.0.2 on 2026-02-14 14:37

from django.db import migrations


def add_disaster_types(apps, schema_editor):
    DisasterType = apps.get_model('disasterplans', 'DisasterType')
    
    disaster_types = [
        {
            'name': 'River Flood',
            'category': 'FLOOD',
            'description': 'A rapid, intense flooding of low-lying areas, usually occurring within six hours of heavy rainfall, dam failure, or rapid snowmelt, often catching people by surprise.',
            'common_regions': ['River valleys', 'Coastal areas', 'Low-lying areas', 'Canada: Quebec (St. Lawrence River valley), British Columbia (Fraser Valley, Okanagan), Manitoba (Red River Valley), Atlantic Canada (New Brunswick\'s Saint John River)']
        },
        {
            'name': 'Flash Flood',
            'category': 'FLOOD',
            'description': 'An overflow of water that submerges land that is typically dry, often caused by heavy rain, prolonged storms, or melting snow.',
            'common_regions': ['Urban areas', 'Mountainous regions', 'Dry riverbeds', 'Canada: Alberta (Calgary), British Columbia (Vancouver), Ontario (Toronto), Quebec (Montreal)']
        },
        {
            'name': 'Forest Fire',
            'category': 'WILDFIRE',
            'description': 'An unplanned, uncontrolled fire burning in vegetative fuels such as forests, grasslands, or brush, which can be triggered by lightning or human activity.',
            'common_regions': ['Dry forests', 'Grasslands', 'Mountain regions', 'Canada: British Columbia, Alberta (foothills/north), Saskatchewan, Manitoba, Ontario, Quebec, and the Northwest Territories']
        },
        {
            'name': 'Extreme Heat',
            'category': 'HEATWAVE',
            'description': 'A prolonged period of excessively hot weather—often with high humidity—lasting for at least several consecutive days and nights, exceeding local temperature averages.',
            'common_regions': ['Desert areas', 'Urban centers', 'Southern regions', 'Canada: British Columbia (interior and coastal), Prairies (Alberta, Saskatchewan), Southern Ontario, Quebec, and increasingly, the Arctic']
        },
        {
            'name': 'Electrical Grid Failure',
            'category': 'POWER_OUTAGE',
            'description': 'A temporary or long-term loss of electric power to an area, frequently caused by extreme weather, infrastructure failure, or high demand.',
            'common_regions': ['All regions', 'Areas prone to storms', 'Remote areas', 'Canada: Ontario and Quebec (ice storms/storms), Atlantic Canada (hurricanes/winter storms), and British Columbia (wind/ice)']
        },
        {
            'name': 'Smog Event',
            'category': 'AIR_POLLUTION',
            'description': 'The presence of harmful substances—such as smoke, particulates, or gases—in the atmosphere, often worsening during wildfires or stagnant weather.',
            'common_regions': ['Industrial areas', 'Major cities', 'Valley regions', 'Canada: B.C., Alberta, Saskatchewan, Manitoba, Northwest Territories, and Northern Ontario/Quebec (wildfire smoke), Ontario and Quebec (urban smog)']
        },
        {
            'name': 'Coastal Erosion',
            'category': 'EROSION',
            'description': 'The geological process where earthen materials (soil, rock) are worn away and transported by natural forces like water, wind, or ice.',
            'common_regions': ['Coastal areas', 'Beachfront properties', 'Islands', 'Canada: Atlantic Canada (Prince Edward Island, Nova Scotia, Newfoundland and Labrador), and the Arctic coast (e.g., Tuktoyaktuk, N.W.T.)']
        },
        {
            'name': 'Tropical Storm',
            'category': 'HURRICANE',
            'description': 'A large, rotating tropical storm with high-speed winds (over 74 mph) and heavy rain that forms over warm ocean waters.',
            'common_regions': ['Coastal regions', 'Islands', 'Tropical areas', 'Canada: Atlantic Canada (Nova Scotia, New Brunswick, Newfoundland and Labrador), and occasionally Quebec and Ontario (remnants of hurricanes)']
        },
        {
            'name': 'Tornado Outbreak',
            'category': 'TORNADO',
            'description': 'A violently rotating column of air extending from a thunderstorm to the ground, capable of causing extreme destruction.',
            'common_regions': ['Plains', 'Midwest', 'Southern states', 'Canada: Southern Ontario, Quebec, and the Prairies (Alberta, Saskatchewan, Manitoba)']
        },
        {
            'name': 'Freezing Event',
            'category': 'COLD_WAVE',
            'description': 'A rapid fall in temperature over a 24-hour period, bringing dangerously low temperatures and sometimes accompanied by high winds.',
            'common_regions': ['Northern regions', 'Mountainous areas', 'Continental interiors', 'Canada: Northern Ontario, Quebec, the Prairies (Alberta, Saskatchewan, Manitoba), and the Arctic (N.W.T., Nunavut)']
        },
        {
            'name': 'Heavy Snowstorm',
            'category': 'BLIZZARD',
            'description': 'A severe snowstorm characterized by strong winds (over 35 mph), low temperatures, and low visibility (less than 1/4 mile) lasting for an extended period.',
            'common_regions': ['Northern states', 'Mountain regions', 'Great Lakes area', 'Canada: Ontario, Quebec, the Prairies (Alberta, Saskatchewan, Manitoba), and the Arctic (N.W.T., Nunavut)']
        },
        {
            'name': 'Seismic Event',
            'category': 'EARTHQUAKE',
            'description': 'A sudden release of energy in the Earth\'s crust that creates seismic waves, resulting in shaking of the ground surface.',
            'common_regions': ['Fault lines', 'Pacific Ring of Fire', 'Tectonic plate boundaries', 'Canada: British Columbia (west coast), Yukon, the Arctic (N.W.T.), the Saint Lawrence and Ottawa River valleys (Quebec/Ontario)']
        },
        {
            'name': 'Snow Avalanche',
            'category': 'AVALANCHE',
            'description': 'A rapid, downslope movement of a large mass of snow, ice, and debris, which can be triggered naturally or by human activity.',
            'common_regions': ['Mountain ranges', 'Ski areas', 'Steep slopes', 'Canada: British Columbia (Rocky Mountains, Coast Mountains), Alberta (Rocky Mountains), and the Arctic (N.W.T., Yukon)']
        }
    ]
    
    for data in disaster_types:
        DisasterType.objects.get_or_create(
            name=data['name'],
            defaults={
                'category': data['category'],
                'description': data['description'],
                'common_regions': data['common_regions']
            }
        )

def remove_disaster_types(apps, schema_editor):
    DisasterType = apps.get_model('disasterplans', 'DisasterType')
    DisasterType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('disasterplans', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_disaster_types, remove_disaster_types),
    ]
    