# Generated by Django 6.0.2 on 2026-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterplans', '0002_add_initial_disaster_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterplan',
            name='common_regions',
            field=models.JSONField(default=list),
        ),
    ]
