# Generated by Django 6.0.2 on 2026-03-18 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterplans', '0003_disasterplan_common_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterplan',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disasterplan',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disasterplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DisasterScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likelihood', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('preparation_steps', models.JSONField(default=list)),
                ('immediate_actions', models.JSONField(default=list)),
                ('during_disaster', models.JSONField(default=list)),
                ('recovery_steps', models.JSONField(default=list)),
                ('critical_supplies', models.JSONField(default=list)),
                ('evacuation_protocols', models.JSONField(default=dict)),
                ('equipment_protection', models.JSONField(default=list)),
                ('communication_plan', models.JSONField(default=dict)),
                ('disaster_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasterplans.disastertype')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='disasterplans.disasterplan')),
            ],
            options={
                'unique_together': {('plan', 'disaster_type')},
            },
        ),
    ]
