# Generated by Django 6.0.2 on 2026-03-21 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterplans', '0004_disasterplan_is_completed_disasterplan_risk_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vulnerability_factors', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('critical_equipment', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('evacuation_requirements', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Species categories',
            },
        ),
        migrations.RemoveField(
            model_name='disasterplan',
            name='emergency_contacts',
        ),
        migrations.RemoveField(
            model_name='disasterplan',
            name='preparation_steps',
        ),
        migrations.RemoveField(
            model_name='disasterplan',
            name='recovery_steps',
        ),
        migrations.RemoveField(
            model_name='disasterplan',
            name='response_steps',
        ),
        migrations.RemoveField(
            model_name='disasterplan',
            name='supplies_needed',
        ),
        migrations.RemoveField(
            model_name='disasterplan',
            name='training_requirements',
        ),
        migrations.AddField(
            model_name='disasterplan',
            name='is_earthquake_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disasterplan',
            name='is_flood_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disasterplan',
            name='is_wildfire_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disasterplan',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='disasterplan',
            name='province',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='disasterscenario',
            name='emergency_contacts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='disasterscenario',
            name='response_steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='disasterscenario',
            name='supplies_needed',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='disasterscenario',
            name='training_requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='disasterplan',
            name='clinic_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disasterplans.clinictypes'),
        ),
        migrations.AddField(
            model_name='disasterplan',
            name='service_types',
            field=models.ManyToManyField(blank=True, to='disasterplans.servicetypes'),
        ),
        migrations.AddField(
            model_name='disasterplan',
            name='species_types',
            field=models.ManyToManyField(blank=True, to='disasterplans.speciestypes'),
        ),
    ]
