# Generated by Django 6.0.4 on 2026-05-11 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterplans', '0005_clinictypes_servicetypes_speciestypes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disasterplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='speciestypes',
            options={'verbose_name': 'Species Category'},
        ),
        migrations.AddField(
            model_name='clinictypes',
            name='code',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('CORPORATE', 'Corporate'), ('MOBILE', 'Mobile'), ('ANIMAL_SHELTER', 'Animal Shelter'), ('TEACHING_HOSPITAL', 'Teaching Hospital'), ('WILDLIFE_FACILITY', 'Wildlife Facility'), ('SMALL_ANIMAL_CLINIC', 'Small Animal Clinic'), ('LARGE_ANIMAL_CLINIC', 'Large Animal Clinic'), ('MIXED_ANIMAL_CLINIC', 'Mixed Animal Clinic')], max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clinictypes',
            name='special_considerations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='disasterplan',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='disasterplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disaster_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disasterplan',
            name='vulnerabilities',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='disasterscenario',
            name='risk_rationale',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='disasterscenario',
            name='service_specific_actions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='disasterscenario',
            name='species_specific_actions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='servicetypes',
            name='backup_requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='servicetypes',
            name='code',
            field=models.CharField(choices=[('GENERAL_VETERINARY_CARE', 'General Veterinary Care'), ('EMERGENCY_OR_CRITICAL_CARE', 'Emergency or Critical Care'), ('URGENT_CARE', 'Urgent Care'), ('SPECIALTY_SERVICES', 'Specialty Services'), ('MOBILE_VETERINARY_SERVICES', 'Mobile Veterinary Services'), ('ANIMAL_SHELTER_SERVICES', 'Animal Shelter Services'), ('TEACHING_HOSPITAL_SERVICES', 'Teaching Hospital Services'), ('WILDLIFE_FACILITY_SERVICES', 'Wildlife Facility Services')], max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicetypes',
            name='unavailability_impact',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='speciestypes',
            name='code',
            field=models.CharField(choices=[('SMALL_ANIMAL', 'Small Animal'), ('LARGE_ANIMAL', 'Large Animal'), ('EQUINE', 'Equine'), ('FELINE', 'Feline'), ('MIXED', 'Mixed'), ('EXOTIC_AND_AVIAN', 'Exotic and Avian')], max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='speciestypes',
            name='critical_supplies',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='speciestypes',
            name='evacuation_priority',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='speciestypes',
            name='handling_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
