# Generated by Django 6.0.2 on 2026-02-18 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('disasterplans', '0003_disasterplan_common_regions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('RECORDS_AND_DOCUMENTS', 'Records and Documents'), ('MEDICAL_SUPPLIES', 'Medical Supplies'), ('SUSTENANCE', 'Sustenance'), ('EVACUATION_HANDLING_AND_TRANSPORTATION_RESOURCES', 'Evacuation Handling and Transportation Resources'), ('SANITATION', 'Sanitation'), ('COMMUNICATION_DEVICES_AND_OPERATIONAL_TOOLS', 'Communication Devices and Operational Tools'), ('FACILITY_AND_SAFETY_GEAR', 'Facility and Safety Gear'), ('SHELTER_AND_BEDDING', 'Shelter and Bedding'), ('STAFF_AND_OWNER_RESOURCES', 'Staff and Owner Resources')], max_length=100)),
                ('is_system_template', models.BooleanField(default=False)),
                ('disaster_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasterplans.disastertype')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicResourceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('review_frequency', models.CharField(choices=[('NONE', 'None'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually'), ('BIANNUALLY', 'Biannually')], default='NONE', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resourcechecklists.checklisttemplate')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_checklists', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('disaster_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_checklists', to='disasterplans.disasterplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('RECORDS_AND_DOCUMENTS', 'Records and Documents'), ('MEDICAL_SUPPLIES', 'Medical Supplies'), ('SUSTENANCE', 'Sustenance'), ('EVACUATION_HANDLING_AND_TRANSPORTATION_RESOURCES', 'Evacuation Handling and Transportation Resources'), ('SANITATION', 'Sanitation'), ('COMMUNICATION_DEVICES_AND_OPERATIONAL_TOOLS', 'Communication Devices and Operational Tools'), ('FACILITY_AND_SAFETY_GEAR', 'Facility and Safety Gear'), ('SHELTER_AND_BEDDING', 'Shelter and Bedding'), ('STAFF_AND_OWNER_RESOURCES', 'Staff and Owner Resources')], max_length=100)),
                ('unit_of_measure', models.CharField(choices=[('BOX', 'Box'), ('BAG', 'Bag'), ('BOTTLE', 'Bottle'), ('CANISTER', 'Canister'), ('CASE', 'Case'), ('PACK', 'Pack'), ('LITER', 'Liter'), ('GALLON', 'Gallon'), ('KILOGRAM', 'Kilogram'), ('GRAM', 'Gram'), ('ROLL', 'Roll'), ('TUBE', 'Tube'), ('UNIT', 'Unit')], default='UNIT', max_length=20)),
                ('units_needed', models.IntegerField(default=1)),
                ('current_units', models.IntegerField(default=0)),
                ('storage_recommendations', models.TextField(blank=True, null=True)),
                ('is_essential', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('ORDERED', 'Ordered'), ('NOT_NEEDED', 'Not Needed')], default='OUT_OF_STOCK', max_length=20)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('supplier_info', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=255, null=True)),
                ('species_specific', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resourcechecklists.checklisttemplate')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
